### ISSUE TITLE
Unable to load sassc-2.1.0.pre1 on Windows

### ISSUE THREAD

**Issue by ashmaroli** [sass/sassc-ruby#125] opened 2019-05-24 14:57 UTC
## Steps to reproduce issue on Windows:
  1. `gem install sassc --pre`
  2. Load IRB: `irb`
  3. Require SassC: `require 'sassc'`

## Output
```
LoadError: Could not open library 'C:/Ruby2.4-x64/lib/ruby/gems/2.4.0/gems/sassc-2.1.0.pre1-x64-mingw32/lib/sassc/2.4/libsass.so': ☺
```

**Comment by ashmaroli** [comment] 2019-05-24 17:43
Apparently, its not just Windows. The following is from a Travis job log.:
```
LoadError:
  Could not open library '/home/travis/build/jekyll/jekyll-sass-converter/vendor/bundle/ruby/2.6.0/gems/sassc-2.1.0.pre1-x86_64-linux/lib/sassc/2.6/libsass.so': 
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by 
  /home/travis/build/jekyll/jekyll-sass-converter/vendor/bundle/ruby/2.6.0/gems/sassc-2.1.0.pre1-x86_64-linux/lib/sassc/2.6/libsass.so)
```

**Comment by betesh** [comment] 2019-05-24 19:51
I haven't been able to test this yet, but googling led me to https://askubuntu.com/a/582910/149571, which recommends `sudo apt-get install libstdc++6`.  Not sure what the windows equivalent is...

**Comment by ahorek** [comment] 2019-05-24 20:00
No, libc has to be compiled statically. There is probably just a parameter that needs to be passed to libsass in extconf.rb

**Comment by betesh** [comment] 2019-05-28 18:45
@ahorek I don't quite understand your comment.  Does this mean a new version of sassc-ruby needs to be released?  How would I build this locally?

**Comment by ahorek** [comment] 2019-05-28 19:17
> Does this mean a new version of sassc-ruby needs to be released?

yes, but prerelease versions are for testing. Use a stable version for now.

> How would I build this locally?

you can always build it directly from the github repository, the problem is only with precompiled versions, so this should work for you. Of course you shouldn't use a testing version in production.
```
Gemfile
gem 'sassc', git: "https://github.com/sass/sassc-ruby.git"
```

this PR does what I meant, take a look https://github.com/sass/sassc-ruby/pull/127 it should be fixed soon

**Comment by glebm** [comment] 2019-06-04 09:56
This is fixed by #127

**Comment by bolandrm** [comment] 2019-06-05 13:21
Version `2.1.0.pre2` released.  Please give it a test!

**Comment by ashmaroli** [comment] 2019-06-05 14:02
@bolandrm Gem was successfully loaded and tested on both Travis CI and AppVeyor CI.

**Comment by betesh** [comment] 2019-06-05 22:02
#127 solved this issue for me, but after upgrading from there to 2.1.0.pre2, I get this error again:

```
LoadError: Could not open library '/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so' : /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so)
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi/library.rb:114:in `block in ffi_lib'
org/jruby/RubyArray.java:2487:in `map'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi/library.rb:84:in `ffi_lib'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/native.rb:10:in `<module:Native>'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/native.rb:6:in `<module:SassC>'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/native.rb:5:in `<main>'
org/jruby/RubyKernel.java:956:in `require'
uri:classloader:/jruby/kernel/kernel.rb:1:in `(root)'
uri:classloader:/jruby/kernel/kernel.rb:13:in `<main>'
org/jruby/RubyKernel.java:956:in `require'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc.rb:31:in `<main>'
org/jruby/RubyKernel.java:956:in `require'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-rails-2.1.1/lib/sassc/rails.rb:1:in `(root)'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-rails-2.1.1/lib/sassc/rails.rb:5:in `<main>'
```

This is on a Centos 7 docker image.  The bundle install right before it works fine.

**Comment by glebm** [comment] 2019-06-06 05:06
@betesh That's strange. Looking at libsass.so precompiled gem (https://rubygems.org/gems/sassc/versions/2.1.0.pre2-x86_64-linux), I can see that libstdc++ is linked statically:

```
ldd ~/tmp/libsass.so 
	linux-vdso.so.1 (0x00007ffc3195b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb371dc3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb371bd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb3724be000)
```

>  The bundle install right before it works fine.

Does it install the precompiled version?

**Comment by betesh** [comment] 2019-06-06 12:39
> Does it install the precompiled version?

It's nested in `platforms :jruby do`.  Does that answer the question?  How else would I check?

> What's the output of ldd '/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so'?

```
[root@875acd391e4e /]# ldd '/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so'
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so)
/root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/my_app/vendor/bundle/jruby/2.3.0/gems/sassc-2.1.0.pre2/lib/sassc/libsass.so)
	linux-vdso.so.1 =>  (0x00007ffd61f9b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007face8272000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007face7f6b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007face7c69000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007face7a53000)
	/lib64/ld-linux-x86-64.so.2 (0x00007face8b47000)
```

**Comment by glebm** [comment] 2019-06-06 13:55
Please try unnesting it from platforms jruby

**Comment by glebm** [comment] 2019-06-06 17:50
@betesh I've just realized that JRuby won't installed precompiled gems for "x86_64-linux", because its RUBY_PLATFORM is "Java", so for JRuby it's compiled from source on install.

Something is wrong in your CentOS container (or possibly but unlikely, the JRuby extconf code). It manages to compile the library with a version of libstdc++ that it then cannot find at runtime. Are you running `bundle install` within the container itself? You always should, because compiled gems cannot be just copied over and expected to work.

**Comment by betesh** [comment] 2019-06-06 20:23
> Are you running bundle install within the container itself?

I was, but only after running it from the host, so when I ran it on the container, it was already installed.  That fixed it, thank you!

**Comment by glebm** [comment] 2019-06-06 20:34
@betesh Here is an example Dockerfile and docker-compose.yml that makes this mistake impossible:

https://github.com/thredded/thredded/blob/master/docker-compose.yml
https://github.com/thredded/thredded/blob/master/Dockerfile

The idea is to never mount `.bundle` or `Gemfile.lock` into the container, so that it always has its own.

**Comment by glebm** [comment] 2019-06-10 18:30
@bolandrm Everything looks good, I think 2.1.0 can be finally released! 😄 :shipit:

**Comment by DirtyF** [comment] 2019-08-12 18:57
@bolandrm Jekyll is waiting on 2.1.0 release to release v4.0, any chance you can put up a release before the end of the week?

**Comment by bolandrm** [comment] 2019-08-19 13:22
2.1.0 released!

**Closed by bolandrm** 2019-08-19 13:22 UTC

**Comment by likeuwill** [comment] 2019-08-20 12:01
> 2.1.0 released!

Get error in docker(rspec tests)
```

LoadError:
--
20 | Could not open library '/usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/libsass.so': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/libsass.so)
```
